name: Feature
description: File a feature request
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing!
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the idea.
      placeholder: ex. Add global search
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Feature
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: 
        **Is your feature request related to a problem? Please describe.**
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

        **Describe the solution you'd like**
        A clear and concise description of what you want to happen.

        **Describe alternatives you've considered**
        A clear and concise description of any alternative solutions or features you've considered.

        **Additional context**
        Add any other context or screenshots about the feature request here.
    validations:
      required: true
